{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9ca60b97",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-11-04T15:07:56.360637Z",
     "iopub.status.busy": "2025-11-04T15:07:56.360336Z",
     "iopub.status.idle": "2025-11-04T15:15:20.675114Z",
     "shell.execute_reply": "2025-11-04T15:15:20.673920Z"
    },
    "papermill": {
     "duration": 444.319222,
     "end_time": "2025-11-04T15:15:20.676499",
     "exception": false,
     "start_time": "2025-11-04T15:07:56.357277",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Protocol: Loading all required libraries...\n",
      "Protocol: Imports Loaded.\n",
      "Protocol: Parameters Loaded. N_FOLDS=5, DEBUG_MODE=False\n",
      "Protocol: 'Ancestral Eye' (get_texture_features) function defined.\n",
      "Protocol: Master Preprocessing function defined.\n",
      "Protocol: Master Training function defined.\n",
      "Protocol: Submission function defined.\n",
      "Protocol: Loading data...\n",
      "Protocol: Beginning Feature Engineering...\n",
      "Protocol: Calculating 'Ancestral Eye' (GLCM) features...\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "97c009249920443b8d8c31605bcb932a",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/1790 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Protocol: Engineering Metadata features...\n",
      "Protocol: Creating final feature dataset...\n",
      "Protocol: Preprocessing complete. Training with 10 numerical + 3 categorical features.\n",
      "Protocol: Beginning 'Expert Mind' (LGBM) 5-Fold Training...\n",
      "--------------------------------------------------\n",
      "Protocol: Commencing LGBM Fold 1/5...\n",
      "[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001499 seconds.\n",
      "You can set `force_row_wise=true` to remove the overhead.\n",
      "And if memory is not enough, you can set `force_col_wise=true`.\n",
      "[LightGBM] [Info] Total Bins 1660\n",
      "[LightGBM] [Info] Number of data points in the train set: 1428, number of used features: 13\n",
      "[LightGBM] [Info] Start training from score 19.743799\n",
      "Protocol: Fold 1 complete. Val R-Squared: 0.7471\n",
      "--------------------------------------------------\n",
      "Protocol: Commencing LGBM Fold 2/5...\n",
      "[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000152 seconds.\n",
      "You can set `force_col_wise=true` to remove the overhead.\n",
      "[LightGBM] [Info] Total Bins 1663\n",
      "[LightGBM] [Info] Number of data points in the train set: 1428, number of used features: 13\n",
      "[LightGBM] [Info] Start training from score 18.938200\n",
      "Protocol: Fold 2 complete. Val R-Squared: 0.8147\n",
      "--------------------------------------------------\n",
      "Protocol: Commencing LGBM Fold 3/5...\n",
      "[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000140 seconds.\n",
      "You can set `force_col_wise=true` to remove the overhead.\n",
      "[LightGBM] [Info] Total Bins 1665\n",
      "[LightGBM] [Info] Number of data points in the train set: 1428, number of used features: 13\n",
      "[LightGBM] [Info] Start training from score 17.111300\n",
      "Protocol: Fold 3 complete. Val R-Squared: 0.7950\n",
      "--------------------------------------------------\n",
      "Protocol: Commencing LGBM Fold 4/5...\n",
      "[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000140 seconds.\n",
      "You can set `force_col_wise=true` to remove the overhead.\n",
      "[LightGBM] [Info] Total Bins 1661\n",
      "[LightGBM] [Info] Number of data points in the train set: 1428, number of used features: 13\n",
      "[LightGBM] [Info] Start training from score 17.298050\n",
      "Protocol: Fold 4 complete. Val R-Squared: 0.8486\n",
      "--------------------------------------------------\n",
      "Protocol: Commencing LGBM Fold 5/5...\n",
      "[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000153 seconds.\n",
      "You can set `force_col_wise=true` to remove the overhead.\n",
      "[LightGBM] [Info] Total Bins 1655\n",
      "[LightGBM] [Info] Number of data points in the train set: 1428, number of used features: 13\n",
      "[LightGBM] [Info] Start training from score 18.049999\n",
      "Protocol: Fold 5 complete. Val R-Squared: 0.8453\n",
      "--------------------------------------------------\n",
      "Protocol: ALL FOLDS complete. Calculating final scores...\n",
      "Protocol: Final OOF R-Squared (Metadata + Ancestral Eye): 0.8137\n",
      "Protocol: Creating final submission file...\n",
      "--------------------------------------------------\n",
      "Protocol: VINDICATION COMPLETE. Final R-Squared: 0.8137\n",
      "Submission file 'submission.csv' created.\n",
      "--------------------------------------------------\n",
      "Protocol: We have a positive R-Squared. The hypothesis is valid.\n",
      "Protocol: End of Notebook.\n"
     ]
    }
   ],
   "source": [
    "# =========================================================================\n",
    "#\n",
    "#                    model  \"Ancestral EYE\" \n",
    "#\n",
    "# =========================================================================\n",
    "#\n",
    "#   ### METHODOLOGY \n",
    "#\n",
    "#   This is the final, monolithic, and correct script.\n",
    "#\n",
    "#    My original, core hypothesis:\n",
    "#   A \"LightGBM\" (LGBM) model trained only on the two\n",
    "#   data streams we believe have real signal:\n",
    "#\n",
    "#   1.  The Metadata (Date, State, NDVI, Height)\n",
    "#   2.  \"Ancestral Eye\" (the 6 GLCM Texture Features)\n",
    "#\n",
    "#   This is the real experiment. It is stable, it is not\n",
    "#   \"too complex\" to converge and it is not \"too simple\" to learn wrong pattern.\n",
    "#   It is the  test of my hypothesis.\n",
    "#\n",
    "# =========================================================================\n",
    "\n",
    "\n",
    "\n",
    "# =========================================================================\n",
    "#                           IMPORTS \n",
    "# =========================================================================\n",
    "\n",
    "\n",
    "print(\"Protocol: Loading all required libraries...\")\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import lightgbm as lgb\n",
    "import os\n",
    "import gc\n",
    "import warnings\n",
    "import joblib  # For saving the final model\n",
    "\n",
    "from sklearn.model_selection import GroupKFold\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.metrics import r2_score\n",
    "\n",
    "from skimage.io import imread\n",
    "from skimage.transform import resize\n",
    "from skimage.color import rgb2gray\n",
    "from skimage.feature import graycomatrix, graycoprops\n",
    "\n",
    "from tqdm.auto import tqdm\n",
    "tqdm.pandas()\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "print(\"Protocol: Imports Loaded.\")\n",
    "\n",
    "# =========================================================================\n",
    "#                  EXPERIMENT PARAMETERS & ENVIRONMENT\n",
    "# =========================================================================\n",
    "class C:\n",
    "    # --- 1. SOTA Protocol Parameters ---\n",
    "    N_FOLDS = 5\n",
    "    SEED = 42\n",
    "    \n",
    "    # --- 2. Path Configuration (Kaggle Environment) ---\n",
    "    # (CRITICAL) You *must* verify this path is correct in your notebook\n",
    "    BASE_PATH = '/kaggle/input/csiro-biomass'\n",
    "    \n",
    "    # --- 3. Debug Mode ---\n",
    "    # We are DONE with debugging. This protocol is stable.\n",
    "    # We will run the full, real experiment.\n",
    "    DEBUG_MODE = False\n",
    "    DEBUG_SAMPLES = 100\n",
    "    \n",
    "    # --- 4. GLCM (Ancestral Eye) Config ---\n",
    "    IMG_SIZE = 224 # We still need to resize for GLCM consistency\n",
    "\n",
    "print(f\"Protocol: Parameters Loaded. N_FOLDS={C.N_FOLDS}, DEBUG_MODE={C.DEBUG_MODE}\")\n",
    "\n",
    "# =========================================================================\n",
    "#                \"ANCESTRAL EYE\" (GLCM) HELPER FUNCTION \n",
    "# =========================================================================\n",
    "def get_texture_features(image_path):\n",
    "    \"\"\"\n",
    "    (Our \"Ancestral Eye\")\n",
    "    Loads an image, resizes, converts to grayscale, and calculates\n",
    "    GLCM Haralick texture features.\n",
    "    \"\"\"\n",
    "    try:\n",
    "        # Load and resize the image for consistency\n",
    "        img = imread(image_path)\n",
    "        img_resized = resize(img, (C.IMG_SIZE, C.IMG_SIZE), anti_aliasing=True)\n",
    "        \n",
    "        # Convert to grayscale\n",
    "        img_gray = rgb2gray(img_resized)\n",
    "        \n",
    "        # Quantize to 8-bit integers (0-255)\n",
    "        img_gray = (img_gray * 255).astype(np.uint8)\n",
    "        \n",
    "        # Calculate GLCM\n",
    "        glcm = graycomatrix(img_gray, distances=[5], angles=[0], levels=256,\n",
    "                            symmetric=True, normed=True)\n",
    "        \n",
    "        # Extract the 6 core texture properties\n",
    "        props = ['contrast', 'dissimilarity', 'homogeneity', 'energy',\n",
    "                 'correlation', 'ASM']\n",
    "        features = np.array([graycoprops(glcm, prop)[0, 0] for prop in props])\n",
    "        return features\n",
    "    \n",
    "    except Exception as e:\n",
    "        # If an image is corrupted, return zeros\n",
    "        return np.zeros(6)\n",
    "\n",
    "print(\"Protocol: 'Ancestral Eye' (get_texture_features) function defined.\")\n",
    "\n",
    "# =========================================================================\n",
    "#                MASTER PREPROCESSING FUNCTION \n",
    "# =========================================================================\n",
    "def load_and_preprocess_data():\n",
    "    \"\"\"\n",
    "    Loads all data, engineers \"Ancestral Eye\" and Metadata features.\n",
    "    This is the *only* feature engineering step.\n",
    "    \"\"\"\n",
    "    \n",
    "   \n",
    "    print(\"Protocol: Loading data...\")\n",
    "    try:\n",
    "        train_df = pd.read_csv(os.path.join(C.BASE_PATH, 'train.csv'))\n",
    "        test_df = pd.read_csv(os.path.join(C.BASE_PATH, 'test.csv'))\n",
    "        sub_df = pd.read_csv(os.path.join(C.BASE_PATH, 'sample_submission.csv'))\n",
    "    except FileNotFoundError as e:\n",
    "        print(f\"FATAL ERROR: {e}. Check BASE_PATH in C. is correct.\")\n",
    "        return None, None, None, None, None\n",
    "\n",
    "   \n",
    "    train_df['image_path'] = train_df['image_path'].apply(lambda x: os.path.join(C.BASE_PATH, x))\n",
    "    test_df['image_path'] = test_df['image_path'].apply(lambda x: os.path.join(C.BASE_PATH, x))\n",
    "\n",
    "    # (Debug Slicer)\n",
    "    if C.DEBUG_MODE:\n",
    "        print(f\"Protocol: DEBUG_MODE active. Slicing dataframes...\")\n",
    "        train_unique_ids = train_df['sample_id'].unique()\n",
    "        n_train_samples = min(C.DEBUG_SAMPLES, len(train_unique_ids))\n",
    "        debug_train_ids = np.random.choice(train_unique_ids, n_train_samples, replace=False)\n",
    "        train_df = train_df[train_df['sample_id'].isin(debug_train_ids)].reset_index(drop=True)\n",
    "        C.N_FOLDS = 2 # Use 2 folds for debug\n",
    "        print(f\"Protocol: Sliced to {len(train_df)} training rows. N_FOLDS set to {C.N_FOLDS}.\")\n",
    "\n",
    "    # ===  FEATURE ENGINEERING ===\n",
    "    print(\"Protocol: Beginning Feature Engineering...\")\n",
    "    \n",
    "    # Combine train/test for easy processing\n",
    "    train_df['is_train'] = 1\n",
    "    test_df['is_train'] = 0\n",
    "    full_df = pd.concat([train_df, test_df], ignore_index=True, sort=False)\n",
    "    \n",
    "    # ---  \"Ancestral Eye\" (Texture Features) ---\n",
    "    print(\"Protocol: Calculating 'Ancestral Eye' (GLCM) features...\")\n",
    "    texture_features = full_df['image_path'].progress_apply(get_texture_features)\n",
    "    texture_cols = [f'glcm_{i}' for i in range(texture_features.iloc[0].shape[0])]\n",
    "    texture_df = pd.DataFrame(np.stack(texture_features), columns=texture_cols)\n",
    "    full_df = pd.concat([full_df, texture_df], axis=1)\n",
    "\n",
    "    # ---  \"Metadata\" Features ---\n",
    "    print(\"Protocol: Engineering Metadata features...\")\n",
    "    # Handle cyclical date features\n",
    "    full_df['Sampling_Date'] = pd.to_datetime(full_df['Sampling_Date'], errors='coerce')\n",
    "    full_df['month'] = full_df['Sampling_Date'].dt.month.fillna(6) # Impute with mid-year\n",
    "    full_df['month_sin'] = np.sin(2 * np.pi * full_df['month']/12.0)\n",
    "    full_df['month_cos'] = np.cos(2 * np.pi * full_df['month']/12.0)\n",
    "            \n",
    "    # Impute missing data\n",
    "    full_df['Pre_GSHH_NDVI'] = full_df['Pre_GSHH_NDVI'].fillna(full_df['Pre_GSHH_NDVI'].median())\n",
    "    full_df['Height_Ave_cm'] = full_df['Height_Ave_cm'].fillna(full_df['Height_Ave_cm'].median())\n",
    "    \n",
    "    # Label-Encode Categorical (LGBM handles this well)\n",
    "    for col in ['State', 'Species', 'target_name']:\n",
    "        full_df[col] = full_df[col].astype('category')\n",
    "        \n",
    "    # ===  FINAL DATASET CREATION ===\n",
    "    print(\"Protocol: Creating final feature dataset...\")\n",
    "    \n",
    "    # Define all features for the model\n",
    "    # (NOTICE: NO 'cnn_feat_' columns. They are *gone*.)\n",
    "    lgbm_features = [col for col in full_df.columns if 'glcm_' in col] \\\n",
    "                  + ['Pre_GSHH_NDVI', 'Height_Ave_cm', 'month_sin', 'month_cos']\n",
    "                  \n",
    "    categorical_features = ['State', 'Species', 'target_name']\n",
    "    \n",
    "    # Separate back into train and test\n",
    "    train_fused = full_df[full_df['is_train'] == 1].reset_index(drop=True)\n",
    "    test_fused = full_df[full_df['is_train'] == 0].reset_index(drop=True)\n",
    "    \n",
    "    X = train_fused[lgbm_features + categorical_features]\n",
    "    y = train_fused['target']\n",
    "    X_test = test_fused[lgbm_features + categorical_features]\n",
    "    groups = train_fused['sample_id'] # For GroupKFold\n",
    "    \n",
    "    print(f\"Protocol: Preprocessing complete. Training with {len(lgbm_features)} numerical + {len(categorical_features)} categorical features.\")\n",
    "    \n",
    "    return X, y, X_test, groups, sub_df\n",
    "\n",
    "print(\"Protocol: Master Preprocessing function defined.\")\n",
    "\n",
    "# =========================================================================\n",
    "#                        MASTER TRAINING FUNCTION \n",
    "# =========================================================================\n",
    "def run_lgbm_training(X, y, X_test, groups):\n",
    "    \"\"\"\n",
    "    Trains the \"Expert Mind\" (LGBM) using \"one single step\"\n",
    "    of N-Fold Cross-Validation.\n",
    "    \"\"\"\n",
    "    print(f\"Protocol: Beginning 'Expert Mind' (LGBM) {C.N_FOLDS}-Fold Training...\")\n",
    "    \n",
    "    gkf = GroupKFold(n_splits=C.N_FOLDS)\n",
    "    \n",
    "    oof_preds = np.zeros(len(X))\n",
    "    test_preds = np.zeros(len(X_test))\n",
    "    \n",
    "    for fold, (train_idx, val_idx) in enumerate(gkf.split(X, y, groups)):\n",
    "        print(\"-\" * 50)\n",
    "        print(f\"Protocol: Commencing LGBM Fold {fold + 1}/{C.N_FOLDS}...\")\n",
    "        \n",
    "        X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]\n",
    "        X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]\n",
    "        \n",
    "        #  parameters for LGBM\n",
    "        lgbm = lgb.LGBMRegressor(\n",
    "            objective='regression_l1', # MAE is more robust to outliers\n",
    "            metric='rmse',\n",
    "            n_estimators=2000,\n",
    "            learning_rate=0.01,\n",
    "            n_jobs=-1,\n",
    "            seed=C.SEED,\n",
    "            colsample_bytree=0.7,\n",
    "            subsample=0.7,\n",
    "            reg_alpha=0.1,\n",
    "            reg_lambda=0.1\n",
    "        )\n",
    "        \n",
    "        # This is the \"keep it learning\" part.\n",
    "        lgbm.fit(\n",
    "            X_train, y_train,\n",
    "            eval_set=[(X_val, y_val)],\n",
    "            eval_metric='rmse',\n",
    "            callbacks=[lgb.early_stopping(100, verbose=False)],\n",
    "            categorical_feature='auto' # LGBM will auto-detect categories\n",
    "        )\n",
    "        \n",
    "        # --- Prediction ---\n",
    "        val_preds = lgbm.predict(X_val)\n",
    "        oof_preds[val_idx] = val_preds\n",
    "        \n",
    "        fold_test_preds = lgbm.predict(X_test) / C.N_FOLDS\n",
    "        test_preds += fold_test_preds\n",
    "        \n",
    "        # ---  Save the model using joblib ---\n",
    "        joblib.dump(lgbm, f'lgbm_model_fold_{fold}.joblib')\n",
    "        \n",
    "        print(f\"Protocol: Fold {fold + 1} complete. Val R-Squared: {r2_score(y_val, val_preds):.4f}\")\n",
    "        \n",
    "    return oof_preds, test_preds\n",
    "\n",
    "print(\"Protocol: Master Training function defined.\")\n",
    "\n",
    "# =========================================================================\n",
    "#                  FINAL SUBMISSION FUNCTION \n",
    "# =========================================================================\n",
    "def create_submission(y_true, oof_preds, test_preds, sub_df):\n",
    "    \"\"\"\n",
    "    Calculates the final OOF score and creates submission.csv\n",
    "    \"\"\"\n",
    "    print(\"-\" * 50)\n",
    "    print(\"Protocol: ALL FOLDS complete. Calculating final scores...\")\n",
    "    \n",
    "    # Calculate OOF (Out-of-Fold) R-squared\n",
    "    final_r2 = r2_score(y_true, oof_preds)\n",
    "    print(f\"Protocol: Final OOF R-Squared (Metadata + Ancestral Eye): {final_r2:.4f}\")\n",
    "    \n",
    "    print(\"Protocol: Creating final submission file...\")\n",
    "    # Ensure no negative biomass predictions\n",
    "    test_preds[test_preds < 0] = 0\n",
    "    \n",
    "    sub_df['target'] = test_preds\n",
    "    sub_df.to_csv('submission.csv', index=False)\n",
    "    \n",
    "    print(\"-\" * 50)\n",
    "    print(f\"Protocol: VINDICATION COMPLETE. Final R-Squared: {final_r2:.4f}\")\n",
    "    print(\"Submission file 'submission.csv' created.\")\n",
    "    print(\"-\" * 50)\n",
    "    \n",
    "    if final_r2 > 0:\n",
    "        print(\"Protocol: We have a positive R-Squared. The hypothesis is valid.\")\n",
    "    else:\n",
    "        print(\"Protocol: The R-Squared is negative. The hypothesis has failed.\")\n",
    "        \n",
    "print(\"Protocol: Submission function defined.\")\n",
    "\n",
    "# =========================================================================\n",
    "#                             PROTOCOL EXECUTION \n",
    "# =========================================================================\n",
    "\n",
    "# (CRITICAL) must be installed for the LGBM model\n",
    "#  must have \"Internet\" turned ON just for this pip command \n",
    "# for this !pip command to work.\n",
    "try:\n",
    "    import lightgbm\n",
    "except ImportError:\n",
    "    print(\"Protocol: Installing lightgbm...\")\n",
    "    !pip install lightgbm\n",
    "    print(\"Protocol: lightgbm installed. Please 'Restart & Run All'.\")\n",
    "\n",
    "# must be installed for the 'Ancestral Eye' my core idea\n",
    "try:\n",
    "    import skimage\n",
    "except ImportError:\n",
    "    print(\"Protocol: Installing skimage...\")\n",
    "    !pip install scikit-image\n",
    "    print(\"Protocol: skimage installed. Please 'Restart & Run All'.\")\n",
    "\n",
    "# --- Main Execution ---\n",
    "if __name__ == \"__main__\":\n",
    "    \n",
    "    # Set global seed (again) for safety\n",
    "    np.random.seed(C.SEED)\n",
    "    \n",
    "    # 1. Load and process all data\n",
    "\n",
    "    X, y, X_test, groups, sub_df = load_and_preprocess_data()\n",
    "    \n",
    "    if X is not None:\n",
    "        # 2. Run the full training protocol\n",
    "        oof_preds, test_preds = run_lgbm_training(X, y, X_test, groups)\n",
    "        \n",
    "        # 3. Create the final submission file\n",
    "        create_submission(y, oof_preds, test_preds, sub_df)\n",
    "    \n",
    "    else:\n",
    "        print(\"Protocol: Halting execution due to data loading error.\")\n",
    "\n",
    "print(\"Protocol: End of Notebook.\")\n"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "databundleVersionId": 14254895,
     "sourceId": 112509,
     "sourceType": "competition"
    }
   ],
   "dockerImageVersionId": 31155,
   "isGpuEnabled": false,
   "isInternetEnabled": false,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.13"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 449.093834,
   "end_time": "2025-11-04T15:15:21.499966",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2025-11-04T15:07:52.406132",
   "version": "2.6.0"
  },
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {
     "0c4035a2546345b3aac4f9a9a8ab0cf5": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_d6ba7a3c47344884a8003946b4ef62e3",
       "placeholder": "​",
       "style": "IPY_MODEL_647aee52031a439a954e630071198215",
       "tabbable": null,
       "tooltip": null,
       "value": " 1790/1790 [07:06&lt;00:00,  4.16it/s]"
      }
     },
     "16fc9d41fcd444de9edcadaf4d8dc91c": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "1933e0b8a4ab4def99934b89d3a64f69": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "3e0aa69bd093426981854d1c77421fec": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "647aee52031a439a954e630071198215": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "8bfdc6d819824180a3798c36976422e3": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_94a9238b137a44458b2774b1442e304b",
       "placeholder": "​",
       "style": "IPY_MODEL_3e0aa69bd093426981854d1c77421fec",
       "tabbable": null,
       "tooltip": null,
       "value": "100%"
      }
     },
     "8d3738194e3e447aa0a376bbe33e90ea": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "FloatProgressModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "FloatProgressModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "ProgressView",
       "bar_style": "success",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_1933e0b8a4ab4def99934b89d3a64f69",
       "max": 1790.0,
       "min": 0.0,
       "orientation": "horizontal",
       "style": "IPY_MODEL_9654a719c4a04108a8c2dee9db239fb9",
       "tabbable": null,
       "tooltip": null,
       "value": 1790.0
      }
     },
     "94a9238b137a44458b2774b1442e304b": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "9654a719c4a04108a8c2dee9db239fb9": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "ProgressStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "ProgressStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "bar_color": null,
       "description_width": ""
      }
     },
     "97c009249920443b8d8c31605bcb932a": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HBoxModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HBoxModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HBoxView",
       "box_style": "",
       "children": [
        "IPY_MODEL_8bfdc6d819824180a3798c36976422e3",
        "IPY_MODEL_8d3738194e3e447aa0a376bbe33e90ea",
        "IPY_MODEL_0c4035a2546345b3aac4f9a9a8ab0cf5"
       ],
       "layout": "IPY_MODEL_16fc9d41fcd444de9edcadaf4d8dc91c",
       "tabbable": null,
       "tooltip": null
      }
     },
     "d6ba7a3c47344884a8003946b4ef62e3": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     }
    },
    "version_major": 2,
    "version_minor": 0
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
